### ISSUE TITLE
Ability to run job manually

### ISSUE THREAD

**Issue by surjikal** [jamesrwhite/minicron#107]
I was trying to debug a job and that feature would have been really useful!

**Comment by RajatGoyal** [comment]
+1 on run a job manually, from web UI

**Comment by andrey-yantsen** [comment]
@jamesrwhite hey, is there any chance that someday you will find some time to fix this issue? :)

**Comment by jamesrwhite** [comment]
It's not really fixing an issue, it's a whole new feature!

minicron relies on cron to trigger it, as such being able to trigger jobs manually requires quite a different approach. Potentially to run a job manually I could add a one off entry to the crontab for a specific time and somehow tidy that up after but that seems like a hack.

The proper way I believe would be to have a minicron "agent" running on each of the remote hosts that sits and listens for commands to execute. There are obvious security concerns with this but provided, as recommended, minicron is not running on the public internet it might be ok.

Given the amount of work required to do this though and the relatively small benefit feature wise it's quite far down on my priority list if I'm being honest. I do want to eventually get to it though, I can't commit to any kind of ETA though :)

If anyone wants to pick this up and give it a go though, feel free! I'll do my best to help.

**Comment by andrey-yantsen** [comment]
Why you want to do this in so complicated way? You have a SSH connection with root user (in most cases) - just run `su USERNAME -c "minicron run CMD >/dev/null 2>&1 </dev/null &"`

**Comment by jamesrwhite** [comment]
Ha, I knew there was another way I'd thought about before. I wrote that
reply late at night, wasn't quite thinking straight!

The only concern I had with doing it this way was that some jobs might take
minutes/hours and I didn't want it to hold the connection open for that
long.. but just like you've some there you could just run it in the
background.
