### ISSUE TITLE
user and group of crontab are changed after job create / edit

### ISSUE THREAD

**Issue by thomasfowler** [jamesrwhite/minicron#109]
Due to a number of reasons, in our environment, minicron can neither run as root nor connect to the servers to be monitored via ssh as root.

As such, I have created a minicron user that has all of the requisite permissions on the client server for the agent to run as well as for it to edit the /etc/crontab file.

However, when the edit is made, the owner and group of the file is set to minicron:minicron thus breaking all cron jobs.

We are running Debian 7 Wheezy Backports

**Comment by jamesrwhite** [comment]
Shouldn't be an issue now given https://github.com/jamesrwhite/minicron/pull/180
