### ISSUE TITLE
Manage localhost CRON without SSH

### ISSUE THREAD

**Issue by jdecool** [jamesrwhite/minicron#113]
Hello, 

I think it could be a good idea to add localhost cron management.

When I want to do that, I need to make a SSH on the current machine.

**Comment by jamesrwhite** [comment]
It is already possible to manage cron's on the same host that minicron resides but as you say this involves the hassle of setting up SSH keys. I think there's a lot more useful features to be worked on than this but I'll definitely keep it in mind for the future.

**Comment by coffenbacher** [comment]
+1 I think this would be really nice. I'm using minicron to basically launch jobs on Docker Swarm - extremely lightweight commands that could easily be run on the hub container. I think this use case may start to be more common relative to many hosts directly exposing SSH.

**Comment by romange** [comment]
:+1:

**Comment by jpettersson** [comment]
+1

**Comment by webts** [comment]
+1

**Comment by joaoricardo000** [comment]
+1
any update on this?
