### ISSUE TITLE
Page load timeout

### ISSUE THREAD

**Issue by Huron** [jamesrwhite/minicron#121]
A page load timeout occurring if the list of execution result is too long or much lines in the execution output. Required a configuration option to limit the length of an execution results list. For example, show N last job results.

**Comment by jamesrwhite** [comment]
In https://github.com/jamesrwhite/minicron/tree/feature/remove-ember I'm working on removing Ember and as part of that I've included a limit on the executions in the sidebar. Eventually this will also include infinite scrolling so it loads more executions as you scroll down.

I know it's annoying but unless it's critical I'm not spending any more time on the current version as I want to fully focus on a bigger revamp. The fix I've suggested before is to manually remove some of the older executions.
