### ISSUE TITLE
TOML::PARSER::SET problem

### ISSUE THREAD

**Issue by gionniboy** [jamesrwhite/minicron#122]
i don't understand what is the problem

root@sensei-dev:/etc# minicron server start --trace
uninitialized constant TOML::Parser::Set

/var/lib/gems/1.9.1/gems/toml-rb-0.3.7/lib/toml/parser.rb:7:in `initialize': uninitialized constant TOML::Parser::Set (NameError)
	from /var/lib/gems/1.9.1/gems/toml-rb-0.3.7/lib/toml.rb:30:in `new'
	from /var/lib/gems/1.9.1/gems/toml-rb-0.3.7/lib/toml.rb:30:in `parse'
	from /var/lib/gems/1.9.1/gems/toml-rb-0.3.7/lib/toml.rb:55:in `load_file'
	from /var/lib/gems/1.9.1/gems/minicron-0.7.6/lib/minicron.rb:70:in `parse_file_config'
	from /var/lib/gems/1.9.1/gems/minicron-0.7.6/lib/minicron/cli.rb:29:in `parse_config'
	from /var/lib/gems/1.9.1/gems/minicron-0.7.6/lib/minicron/cli/commands.rb:67:in `block (2 levels) in add_server_cli_command'
	from /var/lib/gems/1.9.1/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/1.9.1/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/1.9.1/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/1.9.1/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /var/lib/gems/1.9.1/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /var/lib/gems/1.9.1/gems/minicron-0.7.6/lib/minicron/cli.rb:86:in `run'
	from /var/lib/gems/1.9.1/gems/minicron-0.7.6/bin/minicron:14:in `block in <top (required)>'
	from /var/lib/gems/1.9.1/gems/minicron-0.7.6/lib/minicron.rb:127:in `capture_output'
	from /var/lib/gems/1.9.1/gems/minicron-0.7.6/bin/minicron:12:in `<top (required)>'
	from /usr/local/bin/minicron:23:in `load'
	from /usr/local/bin/minicron:23:in `<main>'

during the installation no error no problem found.
help please.

**Comment by jamesrwhite** [comment]
Have you created your own custom config file? I can't reproduce this myself, what OS are you running this on?

**Comment by gionniboy** [comment]
i'm using debian [raspbian+, i tryed first with my .toml file [take from a running minicron 0.7.3 i'm using in another system], error. Then i try with a empty toml file [without my username/pass for database too]
and error too :\

**Comment by gionniboy** [comment]
i tryed to remove from cli.rb the getconfig.opts string, the error goes away but the config file don't be load :\

**Comment by jamesrwhite** [comment]
I think is related to https://github.com/emancu/toml-rb/issues/73, I'm going to do a new release shortly that bumps the minimum version of toml-rb and hopefully that will resolve this for you.

**Comment by jamesrwhite** [comment]
I'll leave this open till you've confirmed it's fixed :)
