### ISSUE TITLE
If the executing user is edited on a job, it doesn't actually update the crontab

### ISSUE THREAD

**Issue by shortjared** [jamesrwhite/minicron#123]
Steps to reproduce.
- Create a job on any host (Should pass) and schedule it (Ex: User `jane`)
- Edit the job and change the user that it is running as (`john`)
- Check the crontab and find it is not updated to run as the new user `john` but is stuck on `jane`
- Try to delete the job, and now you get `Unable to replace '* * * * * john /bin/bash -l -c 'minicron run df'' with '' in the cron file, reason: string not matched`... if you check the crontab, it is still listed as `* * * * * jane /bin/bash -l -c 'minicron run df'`

May work on a fix for this on our end if we get time.

**Comment by jamesrwhite** [comment]
Thanks for reporting this and for the detailed repro steps. I'll try and take a look this weekend.

**Comment by jamesrwhite** [comment]
@shortjared I've tested this myself and it seems to work, it would be great if you could confirm from your side too though?

**Comment by shortjared** [comment]
Confirmed fixed.
