### ISSUE TITLE
Cancelling Add New Job Hides Existing Job Schedules and Executions

### ISSUE THREAD

**Issue by ArcadeRenegade** [jamesrwhite/minicron#131]
Hello,

Under the jobs tab, when you click "Add New Job" and click cancel and then "view" an existing job, the schedules and executions disappear. 

To see them again we must refresh the page and they show up again.

**How it normally looks:**

![image](https://cloud.githubusercontent.com/assets/13874898/9366184/a682e5a4-466a-11e5-9984-4355acf47b1f.png)

**Click "Cancel" at the "Add New Job" page:**

![image](https://cloud.githubusercontent.com/assets/13874898/9366200/c32329ee-466a-11e5-85df-6f4a25e623c4.png)

**Viewing the existing job again:**

![image](https://cloud.githubusercontent.com/assets/13874898/9366220/ee77a444-466a-11e5-9729-f2c227ec8507.png)

**Comment by jamesrwhite** [comment]
Thanks for the very detailed repro steps for this. I've confirmed it is a bug but I'm very close to releasing v0.8 which will almost certainly fix this so as it's not super critical I'm not going to go back and fix it.

I'll close this issue once v0.8 ships.
