### ISSUE TITLE
sqlite default path

### ISSUE THREAD

**Issue by novoxudonoser** [jamesrwhite/minicron#134]
Helow, I want to moun sqlite and key using docker -v option, wher are db and key staord by default at de original  minicron contaner?

**Comment by jamesrwhite** [comment]
In a dockerized version of minicron the SSH keys are in `/root/.ssh`. Currently the SQLite db location isn't configurable and it lives inside the gem which at the time of writing is `/var/lib/gems/1.9.1/gems/minicron-0.7.9/lib/minicron/hub/db/minicron.sqlite3`. This is far from ideal and I hope to improve it in future versions but hopefully this answers your question.

**Comment by ebuildy** [comment]
Could be possible to configure it? So it can be mounted properly for Docker, 

I can do a PR, is it here https://github.com/jamesrwhite/minicron/blob/8e202b00621cd01e13751eb15373102be54dd5f4/lib/minicron.rb#L254 ?

**Comment by jamesrwhite** [comment]
@ebuildy that is the correct place yeah, I believe it _should_ be possible
