### ISSUE TITLE
Package minicron as a binary

### ISSUE THREAD

**Issue by jamesrwhite** [jamesrwhite/minicron#135]
This is to avoid issues with Ruby versions and gems etc, in general it will make it much simpler to deploy minicron.

Current plan is to use https://github.com/phusion/traveling-ruby and https://github.com/jteeuwen/go-bindata although this may change. Essentially a very simple Go program will be responsible for executing the travelling ruby packaged version of minicron.

**Comment by setswei** [comment]
Hey James, Do you need init.d and Systemd start up scripts ? as i have just finished write init.d scripts for ubuntu and debian. and i can easily convert it to systemd for fedora aswell

**Comment by jamesrwhite** [comment]
Sure, that would be great thanks! If this ticket goes according to plan you should just be able to assume that minicron is a single executable binary (not how I imagine your scripts are in their current form).

**Comment by jamesrwhite** [comment]
Put them in the `config` directory perhaps?

**Comment by setswei** [comment]
in my repo i created a folder called "init" but i can move them to the config if you want, i will maintain these scripts for you as you app changes.

**Comment by jamesrwhite** [comment]
Sounds great, thanks!
