### ISSUE TITLE
Authentication error occurred when saving a job's settings

### ISSUE THREAD

**Issue by Huron** [jamesrwhite/minicron#141]
![image](https://cloud.githubusercontent.com/assets/693433/9928968/64da8a2e-5d32-11e5-95b1-7f9835063dfa.png)

I get this error when I try to save job settings. The attempt of connection to the host from the console succeeds with same ssh key.

P.S. And add new job too...

I've got a case for reproducing the error. When I launch minicron from command line by command **minicron server start** it works normally. If I launch it by the init script I've got error when try to make any changes.

```
#!/bin/bash

PID=/var/run/minicron.pid
BIN=/usr/local/bin/minicron

case "$1" in
    start)
        start-stop-daemon --start --pidfile $PID --exec $BIN -- server start
    ;;
    stop)
        $BIN server stop
    ;;
    restart)
        $0 stop
        sleep 3
        $0 start
    ;;
esac
```

**Comment by Huron** [comment]
I've solved my issue.

```
#!/bin/bash

PID=/var/run/minicron.pid
BIN=/usr/local/bin/minicron
HOME=/root

case "$1" in
    start)
        start-stop-daemon --start --pidfile $PID --exec $BIN --chdir $HOME -- server start
    ;;
    stop)
        $BIN server stop
    ;;
    restart)
        $0 stop
        sleep 3
        $0 start
    ;;
esac
```

**Comment by jamesrwhite** [comment]
Ah, I guess without `$HOME` it wasn't able to locate the SSH keys as I'm using `~` in the path to them. 

I'm planning to move the SSH keys from being stored on the file system soon though (https://github.com/jamesrwhite/minicron/issues/124), thanks for the detailed explanation :+1:
