### ISSUE TITLE
init.d and systemd startup scripts

### ISSUE THREAD

**Issue by setswei** [jamesrwhite/minicron#146]
Hey @jamesrwhite 

I thought i would open a issue so i have a reminder to finish this for you, sorry for going quite i have been away for work, i have the ubuntu configuration finished with your new binary version i just need to write the systemd configuration now

also you could link issue #86 with this as i have config in this to set the pid file

**Comment by jamesrwhite** [comment]
Sounds great. I've closed #86 as that's already done actually, I forgot I even had that issue open still!

**Comment by setswei** [comment]
ahh ok, well assign this issue to me i hope to have the systemd configuration written and tested by the end of the week

**Comment by jamesrwhite** [comment]
I can't assign it to you as you're not a collaborator (not yet anyway 😉). Whenever you have the time to finish it is great though, thanks again for your help.

**Comment by jamesrwhite** [comment]
Any progress on this @setswei?

**Comment by setswei** [comment]
hey @jamesrwhite sorry i have been away for a while, i have completed the ubuntu configuration just tweaking it to make it work with the new version, will hopefully have this done today

**Comment by setswei** [comment]
re pull request  #167  for ubuntu/debian scripts
