### ISSUE TITLE
Connection refused - connect(2) for "localhost" port 22

### ISSUE THREAD

**Issue by Pedramrn** [jamesrwhite/minicron#149]
Hello,

I can't connect to localhost machine neither with default config or custom config.

I'm using the 0.8.0 version on ubuntu 15.04

![foo](https://cloud.githubusercontent.com/assets/7994739/10521147/09187d90-737b-11e5-9df4-fae86413dc48.png)

**Comment by jamesrwhite** [comment]
Have you added that public key to your root users `authorized_keys` file? On ubuntu that would be in `/root/.ssh/authorized_keys`, it may not exist so you might need to create it.

**Comment by Pedramrn** [comment]
$ sudo ls -la /root/.ssh
	total 32
	drwx------ 2 root root 4096 Oct 15 20:55 .
	drwx------ 3 root root 4096 Oct 15 20:55 ..
	-rw------- 1 root root 3243 Oct 15 20:55 minicron_host_1_rsa
	-rw-r--r-- 1 root root  748 Oct 15 20:55 minicron_host_1_rsa.pub
	-rw------- 1 root root 1675 Oct 15 20:55 minicron_host_2_rsa
	-rw-r--r-- 1 root root  416 Oct 15 20:55 minicron_host_2_rsa.pub
	-rw------- 1 root root 1675 Oct 15 20:55 minicron_host_3_rsa
	-rw-r--r-- 1 root root  414 Oct 15 20:55 minicron_host_3_rsa.pub

looks like they've added already.

**Comment by jamesrwhite** [comment]
You still need to add all the public keys to your `/root/authorized_keys`, the same as you would on a remote server. minicron doesn't automate this step, you need to do it manually.

**Comment by Pedramrn** [comment]
Thanks, after adding the keys and installing open-ssh, it connects successfully.

However it can't post the results to server after each job.

127.0.0.1 - - [16/Oct/2015:03:04:02 +0330] "POST /api/v1/execution/init HTTP/1.1" 500 50 0.0059        127.0.0.1 - - [16/Oct/2015:03:04:02 +0330] "POST /api/v1/execution/init HTTP/1.1" 500 50 0.0051
127.0.0.1 - - [16/Oct/2015:03:05:04 +0330] "POST /api/v1/execution/init HTTP/1.1" 500 50 0.0066
127.0.0.1 - - [16/Oct/2015:03:05:04 +0330] "POST /api/v1/execution/init HTTP/1.1" 500 50 0.0064
127.0.0.1 - - [16/Oct/2015:03:06:03 +0330] "POST /api/v1/execution/init HTTP/1.1" 500 50 0.0067 127.0.0.1 - - [16/Oct/2015:03:06:03 +0330] "POST /api/v1/execution/init HTTP/1.1" 500 50 0.0070

**Comment by jamesrwhite** [comment]
Yeah this is a bug in the 0.8 release, I'll try and fix that this weekend. I'm going to close this issue and open a separate one.
