### ISSUE TITLE
View issue

### ISSUE THREAD

**Issue by Huron** [jamesrwhite/minicron#152]
![image](https://cloud.githubusercontent.com/assets/693433/10599767/c6c6c064-770d-11e5-8ddf-0a5a82e5eae2.png)

**Comment by jamesrwhite** [comment]
Thanks, I'll sort this in the next release. Probably just by making it scroll horizontally.

**Comment by Huron** [comment]
![image](https://cloud.githubusercontent.com/assets/693433/11029324/e1091e10-86ce-11e5-9b06-777057cd83c2.png)

**Comment by jamesrwhite** [comment]
I'm spoilt by OSX's auto hiding scrollbars, I'll see what I can do about this.

**Comment by jamesrwhite** [comment]
I'll get this out in the next release, the boxes will expand vertically now like so:

![image](https://cloud.githubusercontent.com/assets/640960/11318529/8626db3e-904e-11e5-920f-fedaf20ee03d.png)
