### ISSUE TITLE
Minicron sends alerts for successful execution

### ISSUE THREAD

**Issue by Huron** [jamesrwhite/minicron#154]
![image](https://cloud.githubusercontent.com/assets/693433/10824813/bd7017c2-7e6a-11e5-937f-d73768235e6d.png)
A job is stopping with exit code 0. But I am receiving email alert for each execution of this job.
![image](https://cloud.githubusercontent.com/assets/693433/10824858/f01abee8-7e6a-11e5-80e3-4ba3812d2ee1.png)

**Comment by jamesrwhite** [comment]
What version of minicron are you running?

**Comment by Huron** [comment]
root@g5:~# minicron -v
minicron 0.7.11

**Comment by jamesrwhite** [comment]
Can you confirm if this issue still occurs in https://github.com/jamesrwhite/minicron/releases/tag/v0.8.1, I couldn't replicate it myself. I'm not supporting older versions while minicron is pre 1.0 so I won't be going back to patch the 0.7.x releases.

**Comment by jamesrwhite** [comment]
Closing this, feel free to re-open if you are still having the issue.
