### ISSUE TITLE
minicron doesn't delete a job from crontab after delete it by HUB

### ISSUE THREAD

**Issue by GusevVictor** [jamesrwhite/minicron#157]
subj.

A have setup some jobs, for test. After delete it from GUI, it still exist in my crontab file!

`root@minicron:/opt/minicron-0.8-linux-x86_64# tail -n3 /etc/crontab`
`* * * * * root /bin/bash -l -c 'minicron run '\''touch  /tmp/blah!'\'`
`* * * * * root /bin/bash -l -c 'minicron run '\''touch  /tmp/test_job'\'`
`* * * * * root /bin/bash -l -c 'minicron run '\''ip a'\' `

Is it normal or not?

**Comment by jamesrwhite** [comment]
This is not normal no. Can you confirm that the record(s) are still in the database?
