### ISSUE TITLE
schedules won't be deleted when delete job

### ISSUE THREAD

**Issue by 331299** [jamesrwhite/minicron#160]
contollers/jobs.rb
post '/job/:id/delete' do
...
Minicron::Hub::Job.transaction do
        # Try and delete the job
        Minicron::Hub::Job.destroy(params[:id])
...
end

Minicron::Hub::Job.destroy(params[:id]) should be executed at end of transaction, 
otherwise @job.schedules will be [], so the delete_job will be unused

**Comment by jamesrwhite** [comment]
I've just tested on my local copy of what is soon to be `0.8.1` and I cannot reproduce this issue, it seems to be delete the job and schedule as expected.

**Comment by 331299** [comment]
yes, I have found my problem is the same with #158
