### ISSUE TITLE
Blank lines in cron job output cause "[API Error] Validation failed: Output can't be blank"

### ISSUE THREAD

**Issue by andofrjando** [jamesrwhite/minicron#168]
It seems that blank lines in a job's output will cause the error "[API Error] Validation failed: Output can't be blank". Minicron hub will log output until the blank line, but stops logging when it reaches the blank line.

To produce, consider then following minicron job: `printf 'Hello\nWorld\n'`
Minicron hub will show the job's output as:
```
Hello
World
```
But, consider this job (with one extra line break): `printf 'Hello\n\nWorld\n'`
You would expect:
```
Hello

World
```
but instead minicron shows
```
Hello
[API Error] Validation failed: Output can't be blank
```

**Comment by jamesrwhite** [comment]
Yep, this is an activerecord validation issues on the server side. Thanks for reporting.

**Comment by jamesrwhite** [comment]
I removed the validation and this should be resolved now, I'll include it in the next release. Thanks!

![image](https://cloud.githubusercontent.com/assets/640960/11318550/48c8e006-904f-11e5-9579-68a957f9069c.png)
