### ISSUE TITLE
Add another status badge to indicate "Running"

### ISSUE THREAD

**Issue by robinjoseph08** [jamesrwhite/minicron#173]
Right now, if I have a task running, it's marked with a red X in the list of most recent executions, but if I click that specific execution, I see that it doesn't have a "Finished At" time nor an "Exit Status", so that's how I know it's still running.

I think it'd be nice to have another badge/icon (like a yellow arrow circle) to indicate that it's still in progress at a glance.

**Comment by jamesrwhite** [comment]
Another regression since removing Ember. It should display a yellow icon with a lightning bolt like so: 
![image](https://cloud.githubusercontent.com/assets/640960/11915524/d3ac203a-a6a1-11e5-85ee-dbd9a19973ce.png)
