### ISSUE TITLE
Reverse the order of execution output

### ISSUE THREAD

**Issue by robinjoseph08** [jamesrwhite/minicron#174]
Right now, the output of an execution is actually displayed with the first line produced is at the bottom. So the following code:

```js
for (var i = 0; i < 10; i++) {
  console.log('line ' + i);
}
```

Produces the following:

```
line 9
line 8
line 7
line 6
line 5
line 4
line 3
line 2
line 1
line 0
```

**Comment by jamesrwhite** [comment]
This is a regression since I removed Ember, will fix!

**Comment by jamesrwhite** [comment]
On second thought I can't seem to reproduce what you describe, I tested with `minicron run composer` and for me it displays as I would expect. See (http://cl.ly/e8RL > http://cl.ly/e8g1).

**Comment by jamesrwhite** [comment]
Feel free to re-open if this is still an issue.

**Comment by robinjoseph08** [comment]
That's weird... I'm not sure how composer prints out it's contents, but it might print it all out to stdout before it flushes the stream. Try it with `echo "hello" && echo "world"`:

<img width="490" alt="screen shot 2015-12-20 at 9 38 51 pm" src="https://cloud.githubusercontent.com/assets/2454505/11922977/38101ea8-a762-11e5-9239-d79927bb9477.png">

<img width="746" alt="screen shot 2015-12-20 at 9 39 10 pm" src="https://cloud.githubusercontent.com/assets/2454505/11922967/2c65b7de-a762-11e5-8418-ec706d84bc5b.png">

**Comment by jamesrwhite** [comment]
Weird... still can't reproduce this, the only noticeable difference seems to be you're running the linux build whereas I'm testing this on OSX. Is this version 0.8.4?

![image](https://cloud.githubusercontent.com/assets/640960/11929564/2c8de598-a7d4-11e5-8de7-e9686129efbb.png)

![image](https://cloud.githubusercontent.com/assets/640960/11929575/4832a27a-a7d4-11e5-8dec-ba9d1dce81f5.png)

**Comment by jamesrwhite** [comment]
Even on the linux-x84_64 build I'm still get the expected output ordering, very odd.

**Comment by robinjoseph08** [comment]
Yeah, it's v0.8.4. This is strange.

I took a closer look into the setup of things and I think I might have found a possible culprit. 

It looks like when the execution outputs are loaded to be displayed, an explicit ordering isn't being set. And without an `ORDER BY` clause in SQL, there can be no assumptions made about the ordering of the returning rows. I'm using Postgres in my implementation. Are you using SQLite? It might just be the difference in DBs (and the fact I have a lot more outputs in my table) that's causing this.

If you leave the issue open, I should be able to submit a PR by today to fix it.

**Comment by jamesrwhite** [comment]
Oh that would explain it, I don't test with Postgres very often! MySQL/SQLite default to ordering by the primary key as far as I'm aware but it should be ordered by the `seq` field to make sure it maintains the correct ordering. Nice find!
