### ISSUE TITLE
Cannot run job from UI

### ISSUE THREAD

**Issue by lostinroom** [jamesrwhite/minicron#178]
Hi,

I am using minicron 0.8.4.
connection, /etc write, /etc execute, /crontab read and crontab write are ok.
command line 'minicron run --verbose ls --trace' is ok as well.

My issue is when I create a job from UI, nothing happens.
Number executions never increase.

I have looked at https://github.com/jamesrwhite/minicron/issues/169, it seems $PATH issue.
My PATH value is /usr/local/bin:/usr/bin:/bin:/usr/bin/X11.
My minicron is under /usr/local/bin.
Not sure what you mean by '/path/to/minicron/directory'. Is it /usr/local/bin/minicron?

Can you help?

Thanks

**Comment by jamesrwhite** [comment]
How did you install minicron? Have you tried following/using the [install script](https://github.com/jamesrwhite/minicron/blob/develop/install.sh)?

You may also want to look in the mailbox for the root user as the cron output will have been emailed there.

**Comment by lostinroom** [comment]
Hi,

Yes I used https://github.com/jamesrwhite/minicron/blob/develop/install.sh.
I change the version to 0.8.4 because the latest version that available on https://github.com/jamesrwhite/minicron/releases is 0.8.4.

I found the issue. It is because I didn't use user root when adding host.
Is it mandatory to use user root?

Thanks for your help.

**Comment by jamesrwhite** [comment]
In versions 0.8.x it usually is required yeah, unless you are using another user that has permissions to all those directories/files. It seems weird that the connection test reported everything was ok though..

Either way I'm glad it's working for you now, feel free to re-open this if you have any further questions.
