### ISSUE TITLE
Error with docker

### ISSUE THREAD

**Issue by gjunior-tray** [jamesrwhite/minicron#188]
I cloned the repository and installed with docker, but I got the error:

```sh
$ docker exec e132c2ac1720 minicron server start
/minicron-0.8.4-linux-x86_64/minicron: line 16: /opt/minicron/lib/ruby/bin/ruby: No such file or directory
```

Any idea?

**Comment by gabrielpedepera** [comment]
Hey @gjunior-tray , I had the same problem .. 

I performed the following steps to start service:

```bash
$ docker exec -i -t ​*container_hash*​ bash
```
```bash
$ cp -r minicron-0.8.4-linux-x86_64 /opt/minicron
$ cd /opt/minicron
$ minicron db setup
$ exit
```
```bash
$ docker exec ​*container_hash*​ minicron server start
```
access via IP over port 9292

Ex.: http://docker-ip:9292/

And Works !!

I imagine there must be some problem in the script, but these steps resolved for at least to start service.. =]

**Comment by gjunior-tray** [comment]
Woowwwww, tks!!!

**Comment by jamesrwhite** [comment]
Yeah the `Dockerfile` is quite broken :( It needs to run the install script to move things into the right places. I'll sort this out as soon as I can.

**Comment by jamesrwhite** [comment]
Does the `jamesrwhite/minicron:0.8.4` image work for you guys?

(Try `docker pull jamesrwhite/minicron:0.8.4 && docker exec -it $(docker run -d jamesrwhite/minicron:0.8.4) minicron`)

**Comment by gabrielpedepera** [comment]
@jamesrwhite here works !! :+1:

**Comment by jamesrwhite** [comment]
Thanks! Going to close this then :)
