### ISSUE TITLE
Error when view then edit schedule

### ISSUE THREAD

**Issue by trajche** [jamesrwhite/minicron#189]
Getting an error when editing schedule...

![image](https://cloud.githubusercontent.com/assets/2382019/12481019/41396122-bffb-11e5-8d5d-5a57d84b87e6.png)

I arrive here by clicking "View" on the Schedule, then clicking "Save".

**Comment by jamesrwhite** [comment]
Can you confirm what version of minicron you are running and on what platform please?

**Comment by trajche** [comment]
Using the latest version provided from the installer on Ubuntu 14 (64 bit).

**Comment by jamesrwhite** [comment]
Ahh, this is indeed a bug. That button shouldn't be there! I'm going to fix it as part of the `0.9` release, thanks for reporting.
