### ISSUE TITLE
Issue when using IP instead of 127.0.0.1 for local client

### ISSUE THREAD

**Issue by trajche** [jamesrwhite/minicron#193]
The issue occurs when you setup Minicron as the only server/client by adding itself as a host.
When adding the current server as a host and using the server's public IP (ex: 5.9.120.9) instead of 127.0.0.1 the following happens upon the job execution:

- Minicron automatically creates an additional host with the IP "127.0.0.1"
- Minicron duplicated the job and attaches it to the new host "127.0.0.1"
- The new host is un-editable

When cleaning up and deleting a whole load of mess occurs... By deleting the newly created 127.0.0.1 host, it removes it from the Minicron db but the job stays in crontab.

**Comment by jamesrwhite** [comment]
Thanks, I'll take a look at this when I get a chance. Could you confirm what version of minicron and what platform you are running?

**Comment by trajche** [comment]
Ubuntu 14.04 and Minicron 0.9.0

**Comment by jamesrwhite** [comment]
> When cleaning up and deleting a whole load of mess occurs... By deleting the newly created 127.0.0.1 host, it removes it from the Minicron db but the job stays in crontab.

This part should be resolved as part of the changes I made for #194. Going to check out the rest now.

**Comment by jamesrwhite** [comment]
The only place where I could see this happening is [here](https://github.com/jamesrwhite/minicron/blob/master/lib/minicron/hub/controllers/api/executions.rb#L12-L17). As you can see just above that minicron is judging whether the host for this jobs exists already based on the hosts FQDN (fully qualified domain name), the ip address shouldn't affect this decision.

Are you sure your host has the right FQDN? It should be set to the output of `hostname -f`.

**Comment by jamesrwhite** [comment]
I'm going to close this, feel free to re-open if you are still having an issue.
