### ISSUE TITLE
Editing of job doesn't work until schedule is re-saved

### ISSUE THREAD

**Issue by trajche** [jamesrwhite/minicron#194]
I changed the job for the cron and proceeded to check the crontab.
It wasn't changed there until I re-saved the schedule again.
Edit: Is there a latency when editing the job? Or should it be instant?

**Comment by jamesrwhite** [comment]
Thanks. I can reproduce this on 0.9.0, will check it out when I get a chance.

**Comment by jamesrwhite** [comment]
Will include the fix for this in `0.9.1`, thanks for reporting.
