### ISSUE TITLE
Make it possible to configure display timezone on server

### ISSUE THREAD

**Issue by tttungs** [jamesrwhite/minicron#195]
Hi ,

I want to change timezone UTC with my local time.
How can i do that , is there any option config on /etc/minicron.toml ?

I tried edit timezone on /etc/php5/apache/php.ini but didn't work , any help , thank you.

Best regard,
p/s: my bad english

**Comment by jamesrwhite** [comment]
This might take a bit of work but do you think just making it so that in the web UI the timezone you requested was used? I'd like to keep everything that gets stored in the database in UTC for simplicity.

**Comment by jamesrwhite** [comment]
This is done now for times displayed on the server but everything is still stored in UTC and schedules created will be executed in the timezone that is configured on the given host.
