### ISSUE TITLE
Wrong timezone info

### ISSUE THREAD

**Issue by phsmith** [jamesrwhite/minicron#213]
I installed minicron on a CentOS server and, as I've noticed, it's using UTC timezone, not the system timezone info that is set to 'America/Sao_Paulo'.

**Comment by jamesrwhite** [comment]
The next release will make the display timezone configurable, see: https://github.com/jamesrwhite/minicron/blob/develop/config/minicron.toml#L27

Related to: https://github.com/jamesrwhite/minicron/issues/195

**Comment by phsmith** [comment]
Ah! OK! Thanks for the answer.
