### ISSUE TITLE
connection to localhost expires

### ISSUE THREAD

**Issue by romange** [jamesrwhite/minicron#214]
At some point web gui fails to connect to its hosts and job editing fails.
Test Connection fails.
Restart solves the problem but it happens consistently.
My OS: ubuntu 14.04.

**Comment by jamesrwhite** [comment]
Hmm, this sounds weird. It's making a new connection attempt each time so it's not like restarting would cause it to open a new connection or anything.

If/when it happens again could you try manually connecting to the host using the key that minicron uses and see what it says? The command should be something like this:

`ssh -i ~/.ssh/minicron_host_*ID*_rsa -v *user*@127.0.0.1`

Where *ID* and *user* are details you can get from viewing the host in the GUI.

**Comment by jamesrwhite** [comment]
Closing this unless you have any more info to provide, feel free to re-open.
