### ISSUE TITLE
Re-open MySQL connection on failure

### ISSUE THREAD

**Issue by Rido** [jamesrwhite/minicron#216]
The MySQL connection closes sometimes and the web interface is no longer working then. It would be nice to check the MySQL connection and try to reopen it.

```
ActiveRecord::StatementInvalid at /
Mysql2::Error: closed MySQL connection: SELECT `executions`.* FROM `executions` ORDER BY `executions`.`created_at` DESC, `executions`.`started_at` DESC LIMIT 1

Ruby	/opt/minicron/lib/vendor/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb: in query, line 305
```

BTW: When can we expect another release? :innocent:

**Comment by jamesrwhite** [comment]
The next release will be whenever I have time to finish it :smile:
