### ISSUE TITLE
Make dependencies optional

### ISSUE THREAD

**Issue by Paxa** [jamesrwhite/minicron#226]
Do you think it will be better to make this dependencies optional?

* thin (If I want to mount it as engine in rails app)
* sshkey (if I don't need to edit cron tab)
* net-ssh
* mail
* twilio-ruby
* slack-notifier
* pagerduty
* aws-sdk
* sqlite3 (activerecord will try to load gem automatically for specified `:adapter`)
* mysql2
* pg

**Comment by jamesrwhite** [comment]
At the moment I'm only really focusing on supporting minicron being run in it's packaged form not as a standalone gem so making any dependencies optional doesn't really make much of a difference since I'm pre-building everything.

Feel free to re-open if you have any other thoughts. Thanks!
