### ISSUE TITLE
add containers as host

### ISSUE THREAD

**Issue by abipit** [jamesrwhite/minicron#229]
Hello,
I installed minicron in a docker container and I would add hosts. But my hosts are also containers, is it possible ?
Thanks

**Comment by jamesrwhite** [comment]
If I'm understanding you correctly provided your docker containers can talk to each other this should be possible yes.

**Comment by abipit** [comment]
Ok, thank you for your answer. So how can I add a host where this host is a container ?

For example, I have my OS (coreOS), I have a container "mysql" and your container "minicron".
With your container minicron, I want to launch a cron on my container mysql. How can I do ?
Thank you

**Comment by abipit** [comment]
Hello, 
if is it possible, how can I do please ?

**Comment by ebuildy** [comment]
You still need SSH to execute command. I think the feature you want (I want the same ^^), is to execute command via ``docker exec`` ?
