### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Huron** [jamesrwhite/minicron#231]
The error has occurred on the job page
![image](https://cloud.githubusercontent.com/assets/693433/16440754/841546dc-3dcd-11e6-8574-cfbe235b095e.png)

Installed version is 0.9.5. I've tested 0.9.4, 0.9.3 too. But only 0.9.2 works normally.

**Comment by jamesrwhite** [comment]
Can you try running `minicron db:migrate`? The enabled field was added in the `0.9.3` release and I forgot to put in the release notes you need to run migrations.

**Comment by Huron** [comment]
Thanks so much! The migrate command has solved the problem.
