### ISSUE TITLE
Wrong db host connection

### ISSUE THREAD

**Issue by Rido** [jamesrwhite/minicron#233]
The last time I got some problems with the database connections. For some reason Minicron is using the wrong database host.

**Error message:**
`Mysql2::Error: SELECT command denied to user 'minicron'@'mailtester.xxxxx.lan' for table 'executions': SELECT `executions`.* FROM `executions` ORDER BY `executions`.`created_at` DESC, `executions`.`started_at` DESC LIMIT 1`

**My config is:**

``` [server]
host = "127.0.0.1"
port = 9292
path = "/"
pid_file = "/tmp/minicron.pid"
timezone = "Europe/Amsterdam"
  [server.session]
  name = "minicron.session"
  domain = "127.0.0.1"
  path = "/"
  ttl = 86400
  secret = "xxxxx"
  [server.database]
  type = "mysql" # [mysql, postgresql, sqlite]
  # The options below are for mysql and postgresql only
  host = "192.168.12.234"
  database = "minicron"
  username = "minicron"
  password = "xxxxx"
  [server.ssh]
  connect_timeout = 5
```

Is there a fix for this problem or am I doing something wrong?

Thanks!

**Comment by jamesrwhite** [comment]
Have you restarted minicron since you changed the configuration? It opens a connection once at startup and will not re-connect if the config changes.

**Comment by Rido** [comment]
Yes, I restarted Minicron several times, but each time I get this error.

**Comment by eduardogalbiati** [comment]
It seems like the user 'minicron' on mysql server does not have permission to read (perform a SELECT) on database, did u checked this permissions on mysqlserver?

**Comment by jamesrwhite** [comment]
I think this is more likely to be a permissions issue in MySQL than minicron itself as mentioned above so I'm closing this.
