### ISSUE TITLE
Execution of existing job causes new job to be created in Minicron Hub 

### ISSUE THREAD

**Issue by andofrjando** [jamesrwhite/minicron#235]
Using Minicron 0.9.6, fresh new installation on Ubuntu 16.04.

I create a job in the Web Gui, and it is created in the crontab on the remote computer no problems. When that job executes (either at the scheduled time or by manually running it from the Minicron web interface), Minicron server doesn't detect the execution as the existing job, so it creates a new one using the command itself as the name. 
As you can see in the screen shot below, there's a job 'Upgrade Plex' but when that job runs, the 'executions' table at the bottom stays blank and a new job is created with the command as the title.
![screen](https://cloud.githubusercontent.com/assets/5728285/16892439/965cf166-4b45-11e6-8d11-8e149505ee51.png)

**Comment by andofrjando** [comment]
I think this might have been caused by the remote computer configuration. The host that I had set up was something like `plex.myfqdn.com`, but when the job ran the FQDN for the host was reported back to minicron server as simply `plex`. 
In minicron server, I changed the FQDN of the host from `plex.myfqdn.com` to `plex` and it has resolved the issue. I can leave the `Host`field as the entire FQDN though. I'm not sure what the difference between the `FQDN` and `Host` fields are in minicron server.

**Comment by jamesrwhite** [comment]
Yeah, the host is what minicron connects to e.g. `127.0.0.1`, `10.1.2.3.4` or `db.example.com` whereas the FQDN is how it identifies the server an incoming job comes from. It gets this from the output of `hostname -f` on the server the job runs from. Feel free to re-open this if you have any further questions :)
