### ISSUE TITLE
Test Connection error

### ISSUE THREAD

**Issue by knexp** [jamesrwhite/minicron#237]
Hi ,

When I add host in UI, I always get test connection fails ,

But i tried to connect the host server with ssh in terminal it is working.

ssh -v -i ~/.ssh/minicron_host_2_rsa root@ip-10-167-106-222

why it says Test connection fails, am i missing something?

**Comment by jamesrwhite** [comment]
I'm planning to remove this feature as part of the first major version, as such I'm closing this issue.
