### ISSUE TITLE
Deleting a job causes alerts view to fail

### ISSUE THREAD

**Issue by JonasBonno** [jamesrwhite/minicron#240]
Is this only me? Are there a fix or workaround?

NoMethodError at /alerts
undefined method `id' for nil:NilClass
Ruby
/opt/minicron/lib/vendor/ruby/2.2.0/gems/minicron-0.9.6.1467466137/lib/minicron/hub/views/alerts/index.erb: in block (2 levels) in singleton class, line 22 
Web
GET [MinicronServerURL]/alerts

Line 22:  #{route_prefix}/job/#{alert.job.id}" %>"> <%= alert.job.safe_name %
(deleted some of the <> due to github reading them)

**Comment by JonasBonno** [comment]
Íf I delete the schedules in a job and thereafter deletes the job then everything is fine.
Alerts can't handle deleting jobs with schedules.

**Comment by jamesrwhite** [comment]
Interesting, thanks for looking into it a bit more, very helpful :)

**Comment by jamesrwhite** [comment]
From what I can see I've fixed this in `0.9.7`, please re-open this if it's not the case.
