### ISSUE TITLE
What's the high level architecture?

### ISSUE THREAD

**Issue by chris-fa** [jamesrwhite/minicron#244]
Hello I'm new to minicron and it looks wonderful. I'm confused of the high level architecture, so I would like some clarification if possible.

Basically I don't understand where is everything supposed to be installed, specially cause there is such a thing as a "host" where minicron connects via SSH. So my question is: where should I install minicron?

Is it on the production server that I want the cronjobs to be run?  Or I should install minicron anywhere else and it will SSH to my production server to run cronjobs there?

**Comment by jamesrwhite** [comment]
Hey,

`minicron` needs to be installed on both the server(s) you want to run jobs on and it needs to itself be running somewhere, this could be on the same server or a different one, to collect the output of these jobs.

Hopefully that clears it up, feel free to re-open this if you still aren't sure 👍
