### ISSUE TITLE
minicron run issue

### ISSUE THREAD

**Issue by imrantune** [jamesrwhite/minicron#247]
I had tried with mysql this command
`minicron run 'mysqldump db > backup.sql'`
showing this error

too many bad responses after 0 requests on 47245026356840, last used 1481100333.9302518 seconds ago

**Comment by jamesrwhite** [comment]
Are you still having this issue?

**Comment by jamesrwhite** [comment]
Closing this due to lack of a reply, feel free to re-open if needed.
