### ISSUE TITLE
Support for crontab commands that add comment lines on top (ie: cronie)

### ISSUE THREAD

**Issue by marchioman** [jamesrwhite/minicron#251]
Scheduling jobs with cronie (default cron daemon on SLES et al) doesn't work as cronie's crontab(1) adds three lines of comments on top of crontab(5) to alert user not to directly edit the file.
Workaround: add 
`| grep -vE '^# (DO NOT|\(/tmp/|\(Cronie)'`
at row199, column 46 of file lib/minicron/cron.rb

**Comment by jamesrwhite** [comment]
In version 1.0 that I'm currently actively working on I'm planning to remove altering crontabs directly so I won't be resolving this issue. Thank you for reporting it though.
