### ISSUE TITLE
How can I uninstall minicron?

### ISSUE THREAD

**Issue by ivanstan** [jamesrwhite/minicron#253]

**Comment by jamesrwhite** [comment]
1. Remove any hosts from minicron by deleting them from the ui
2. Stop the minicron server
3. `rm /usr/local/bin/minicron`
4. `rm -rf /opt/minicron`

That should do it. Feel free to re-open if that doesn't work.

**Comment by ivanstan** [comment]
and `rm /etc/minicron.toml` I suppose! Thanks!
