### ISSUE TITLE
Alerts from remote machine

### ISSUE THREAD

**Issue by ivanstan** [jamesrwhite/minicron#254]
I have added new host, and I'm able to perform CRUD operations on remote machine but no execution feedback. I'm probably doing something wrong? Maybe documentation needs to be a bit more detailed for such cases.

**Comment by ivanstan** [comment]
I have minicron installed on remote host, but database is not setup for that machine. Should all instances of minicron on remote machines point to the host database running on machine that I use for management?

**Comment by jamesrwhite** [comment]
The database only needs to exist on the server the web ui runs on, when a job is actually run the data is transmitted over http(s).

**Comment by jamesrwhite** [comment]
Closing this due to lack of a reply, feel free to re-open if needed.
