### ISSUE TITLE
What happens if two crons are scheduled at the same time?

### ISSUE THREAD

**Issue by jamesrwhite** [jamesrwhite/minicron#26]
This will most likely break the alerting system as it will not be able to tell which schedule is for which execution.

Not sure how to solve this right now but I'm leaving this here as a reminder.

**Comment by Lavoaster** [comment]
Is this still an issue? As in, do I need to keep it in mind when using Minicron?

**Comment by jamesrwhite** [comment]
I've just reviewed the code and I don't think this will be an issue actually. I'm leaving this open until I have time to confirm it 100% though.

**Comment by jamesrwhite** [comment]
Fairly sure this isn't an issue 🙌
