### ISSUE TITLE
changed the time zone in config file..But not reflecting 

### ISSUE THREAD

**Issue by saravana91mobiles** [jamesrwhite/minicron#262]
HI,

I have changed the time zone in minicron.toml but still the time is UTC only..in mysql all enteries are inserting with an timeformat of UTC only.

Kinldy help me

**Comment by saravana91mobiles** [comment]
timezone = "Mumbai"

**Comment by jamesrwhite** [comment]
Did you restart the server after making this change?

**Comment by saravana91mobiles** [comment]
nope.. i will restart and check.
Thank u

**Comment by saravana91mobiles** [comment]
now working fine thxs
