### ISSUE TITLE
minicron monitor script on supervisor issue

### ISSUE THREAD

**Issue by monday41** [jamesrwhite/minicron#266]
I change the `supervisor` config file like this.

```
[program:ProcessScript]
command=minicron run "php /data/apps/script.php"
numprocs=1
startsecs = 3
startretries = 5
user=work
stdout_logfile = /data/logs/script.log
stderr_logfile = /data/logs/script.log
redirect_stderr = true
autostart=true
autorestart=true
```

If this script exited, minicron server can't get the execution info.

I don't know the reason.
Do you have any hint for me?

**Comment by jamesrwhite** [comment]
Does it work correctly outside of supervisor?

**Comment by monday41** [comment]
Sorry,It's my mistake. 
minicron can trace the start time, but it can't trace the finish time.
Because when I stop the script by supervisorctl, it just kill the pid.

**Comment by jamesrwhite** [comment]
👍
