### ISSUE TITLE
any way to ignore some exit_status

### ISSUE THREAD

**Issue by saravana91mobiles** [jamesrwhite/minicron#268]
i am using SOLO service to run a file.. the file runs on every minute.

so minicron is triggering an error - 'solo(6088): Address already in use '.. and exit_status = 98

is there is any way where can bypass few exit_status ??

Thanks

**Comment by jamesrwhite** [comment]
Could you clarify what you mean by this and give an example? What is `SOLO`? Are you saying you're running a job from minicron which itself is returning an exit status of > 0?

By definition an exit status of above 0 indicates an error has occurred so minicron rightly treats this as such. I don't think it would be a good idea to allow bypassing this.

**Comment by saravana91mobiles** [comment]
http://kvz.io/blog/2012/12/31/lock-your-cronjobs/
 
solo is a very simple script that prevents a program from running more than one copy at a time. It is useful with cron to make sure that a job doesn’t run before a previous one has finished.

* * * * * /usr/bin/solo -port=3000 /path/to/yourscript.sh
so what happen every minute  it will try to start the file yourscript.sh...but in port 3000 there might be  the same file running so  minircon trigger an alert called 'solo(6088): Address already in use '

Thanks
Saravana

**Comment by jamesrwhite** [comment]
I don't think allowing ignoring non zero exit statuses is the right solution to this, https://github.com/jamesrwhite/minicron/issues/164 would be a better solution in my opinion.
