### ISSUE TITLE
what are the plans for 1.0?

### ISSUE THREAD

**Issue by danielmroberts** [jamesrwhite/minicron#271]
I was evaluating minicron for the company I work for when the roadmap was switched to not include job creation. Just to be clear, is the intention that you will be able to add hosts, import jobs and then monitor them on going? Will minicron usage by cron job commands need to be implemented manually? Just trying to get an solid understanding. Thanks

**Comment by jamesrwhite** [comment]
That is correct yeah, you will still be able to create hosts/jobs/schedules alerts from minicron but you will need to place those in your cron tab yourself. I'm planning to make it easy to export the data either manually through the UI or via an API endpoint so you can integrate it with any configuration management software you're using (chef, puppet etc).

**Comment by jamesrwhite** [comment]
Closing this, feel free to re-open if you have any follow up questions.
