### ISSUE TITLE
Installation unclear, can't run the service

### ISSUE THREAD

**Issue by pesseyjulien** [jamesrwhite/minicron#274]
Hi,

I'm sorry but I did follow the installation process to the letter, but I'm getting the enclosed error.

This is my nginx config :

        location /minicron {
            # Pass the real ip address of the user to minicron
            proxy_set_header X-Real-IP $remote_addr;

            # minicron defaults to running on port 9292, if you change
            # this you also need to change your minicron.toml config
            proxy_pass http://127.0.0.1:9292;
        }
Any idea why ?

Thanks in advance,
Julien

**Comment by jamesrwhite** [comment]
What is the error?

**Comment by pesseyjulien** [comment]
Sorry, I thought my screenshot was uploaded. Here it's !
<img width="757" alt="capture d ecran 2017-03-26 a 19 12 08" src="https://cloud.githubusercontent.com/assets/10850944/24333578/b8007432-125a-11e7-9c84-4603bcff24e3.png">

**Comment by jamesrwhite** [comment]
By default minicron expects that is running at the root i.e. `/`, if you want it to be on `/minicron` you need to change the [`server.path`](https://github.com/jamesrwhite/minicron/blob/master/config/minicron.toml#L33) and [`client.server.path`](https://github.com/jamesrwhite/minicron/blob/master/config/minicron.toml#L15) configuration variables.

**Comment by pesseyjulien** [comment]
Indeed, it does work better now :)

Thanks for the quick help. 

One more thing if I may, how can I install assets ?

**Comment by jamesrwhite** [comment]
What do you mean by assets?

**Comment by pesseyjulien** [comment]
css/js, because for now this is what I see :
<img width="1407" alt="capture d ecran 2017-03-26 a 19 40 54" src="https://cloud.githubusercontent.com/assets/10850944/24333652/265a454c-125c-11e7-9aa9-e430d98709c7.png">

**Comment by pesseyjulien** [comment]
I'm guessing it's because I'm running it from /minicron.

**Comment by jamesrwhite** [comment]
If you look in the page source do the links to the assets include `/minicron`?

**Comment by pesseyjulien** [comment]
They do : <link rel='stylesheet' href='/minicron/css/all.55b9f57137ab753d66cf6c82f671a475.css' media='screen' />

**Comment by pesseyjulien** [comment]
I change my nginx config file so assets would load, thanks !

Quick question, how can I specify an ssh key so I can connect to my host ?

Right now I have an 'Authentication failed for user' error.
