### ISSUE TITLE
Execution Status is 0, but got failed email alert

### ISSUE THREAD

**Issue by SqlAdmin** [jamesrwhite/minicron#276]
Im using flock for all scripts, so in case if the previous job is still running then the next job will never run. So in minicron its show eexcution status is 0, this is fine, but I got Job failed alert. Can you please make the alerts only the exeution status is 255?

**Comment by jamesrwhite** [comment]
Technically any status above 0 indicates the command has failed. See the discussion on https://github.com/jamesrwhite/minicron/issues/268, I think that is the right way to go instead of ignoring certain statuses.
