### ISSUE TITLE
Meaning of Exit Status Code

### ISSUE THREAD

**Issue by SqlAdmin** [jamesrwhite/minicron#278]
Can you please list out the status codes and meaning ?

**Comment by jamesrwhite** [comment]
What do you mean by status codes?

**Comment by SqlAdmin** [comment]
Oh sorry, its Exit Status, updated the question.

**Comment by jamesrwhite** [comment]
It should just be forwarding the exit status reported by the command: http://www.tldp.org/LDP/abs/html/exit-status.html. These are from the OS, not minicron.

**Comment by SqlAdmin** [comment]
Can I enable alerts based on exit code?
