### ISSUE TITLE
Slack message should have name of failed job

### ISSUE THREAD

**Issue by jdforsythe** [jamesrwhite/minicron#283]
The slack message looks like this:

```
Execution #4 of Job #5 failed
```

This doesn't tell you what job it is unless you go look at the web site. I'm not a ruby dev, but would be willing to look into it. How hard would it be to add the job name and host name to the message? Something like this:

```
Execution #4 of Job #5 (Some scheduled job name) on host somehost.local failed
```

It'd also be cool to have a direct link to the failed execution.

**Comment by jamesrwhite** [comment]
It would be [here](https://github.com/jamesrwhite/minicron/blob/master/lib/minicron/alert/slack.rb) you could change the message. All the data you need to do that should be in `options[:job]`.
