### ISSUE TITLE
What has happened to the docs? Too difficult to get started :/

### ISSUE THREAD

**Issue by LaszloHont** [jamesrwhite/minicron#285]
To be able to use minicron the user has to know:
* That the docs on the homepage (github) refer to the development version and should be ignored
* That they should clone the repo using a different branch otherwise they will get the development version
* That they should read the docs, go to the recommended release url, then use the git directory to get to the docs again to do the install.

It's not easy! (and I swear this use to be much easier)

**Comment by jamesrwhite** [comment]
Thanks, I've switched the default branch back to master for now. I'll think about how better to make the future of the project clear.

**Comment by LaszloHont** [comment]
Some very nice documentation there!
