### ISSUE TITLE
Make database port configurable

### ISSUE THREAD

**Issue by dhuckins** [jamesrwhite/minicron#291]
searched for this but couldn't find anything about it. is it possible to set a port (different from the default) when connecting a mysql or postgres database?

**Comment by jamesrwhite** [comment]
Currently the port isn't configurable no, bit of an oversight on my part there. It should be relatively easy to add though if you fancy having a go at it.

**Comment by dhuckins** [comment]
Seems like it, already scoped it out a bit
https://github.com/jamesrwhite/minicron/blob/master/lib/minicron.rb#L244

would have to add it to the config no? each database (mysql/postgres) have different default ports 
maybe put here? 
https://github.com/jamesrwhite/minicron/blob/master/lib/minicron.rb#L223

thanks
