### ISSUE TITLE
error: setupterm: could not find terminfo database

### ISSUE THREAD

**Issue by LaszloHont** [jamesrwhite/minicron#293]
When I run a minicron job from cron, I get this error:

`error: setupterm: could not find terminfo database`

But not when I run the minicron job from the command-line or from cron directly (not through minicron).

Any ideas why this is? Thank you.

**Comment by jamesrwhite** [comment]
[This](https://stackoverflow.com/a/21571407/483271) seems to suggest setting two environment variables should fix it. You could add those to your job definition if it relies on them to work correctly.

**Comment by LaszloHont** [comment]
I tried that, but it didn't help. I will investigate!

**Comment by jamesrwhite** [comment]
Closing as this is almost a year old now, feel free to re-open if you still have this issue.
