### ISSUE TITLE
minicron do nothing

### ISSUE THREAD

**Issue by phuthinh2202** [jamesrwhite/minicron#300]
i run minicron docker follow the link: https://hub.docker.com/r/jamesrwhite/minicron/
- add host, import ssh public key into host.
- create job and run job but minicron do nothing.
Pls help!

**Comment by ebuildy** [comment]
Heu, it's hard to help you with just "do nothing".

Please, add the Docker / minicron version you are using, and if cron is running fine on your minicron container.

**Comment by jamesrwhite** [comment]
Closing unless more info is provided.
