### ISSUE TITLE
Add support for crontabs in /etc/cron.d

### ISSUE THREAD

**Issue by jamesrwhite** [jamesrwhite/minicron#74]
Support for crontabs in this dir varies per implementation, will need to research this.

**Comment by dan-ding** [comment]
Perhaps have it auto-check? If /etc/cron.d/ exists then use it (or check the cron configuration?), if not fall back to /etc/crontab?

/etc/cron.d/minicron seems nicer and more manage-able on a few levels.

**Comment by jamesrwhite** [comment]
With https://github.com/jamesrwhite/minicron/pull/180 I don't think this is relevant anymore.
