### ISSUE TITLE
Add example Apache config

### ISSUE THREAD

**Issue by jamesrwhite** [jamesrwhite/minicron#84]

**Comment by setswei** [comment]
Do you have a example of this, if not do you want one ?

**Comment by jamesrwhite** [comment]
If you could provide one that would be great.

It should be simpler now also as the requirement for websocket support no longer exists as I'm planning to replace them with Server Side Events/a service like Pusher in the next release.

**Comment by setswei** [comment]
I will put a copy up tommorow when i get into the office and include
documentation for that and adding authentication

**Comment by setswei** [comment]
I have created a pull request to your develop branch with the example and documentation

**Comment by jamesrwhite** [comment]
Thank you!
